### ISSUE TITLE
%FZF_DEFAULT_COMMAND% not working in cmd.exe

### ISSUE THREAD

**Issue by step-** [genotrance/ff#2]
Cut and pasted from a cmd.exe console window in Win10:
```
set "$FZF_DEFAULT_CMD=dir /s/b"
fzf
   ... (this works)
ff
[default command failed - $FZF_DEFAULT_COMMAND required]
```
I tried also `set "FZF_DEFAULT_CMD=dir /s/b"` without avail.
It's as though ff clears the environment before running fzf. Does it?
So, anyway, I can't get ff to work in a cmd.exe console.
Do you run ff inside cmd.exe?

**Comment by genotrance** [comment]
Yes, ff overrides the environment variable for fzf. You can use the ```-s``` flag to affect it.

You can also have a custom selection by default for a given action. Check out the [README](https://github.com/genotrance/ff/blob/master/README.md) for details under the ```Selection``` menu and [ff.cfg](https://github.com/genotrance/ff/blob/master/ff.cfg) for examples.

**Comment by step-** [comment]
OK, thank you. I had read before about the `-s` option, but somehow I got confused about what it's supposed to do, so I started looking elsewhere for way to specify the FZF_DEFAULT_COMMAND variable. The usage section in README says:
```
  -s <select>     Content to populate the fzf menu
                    file, dir or *.xyz shortcuts
                    or command to execute
```
I think it's the use of the words "fzf menu" that got me confused. I think of it as a result list rather than as a menu. I should have been more flexible in interpreting that sentence.

So I tried
`ff -s "dir /s/b"` and it worked by displaying all pathnames (recursive). OK.
`ff -s *.zip` and it worked by displaying all zip archive file names. OK
`ff -s EXISTING_DIR` and got error message "[default command failed - $FZF_DEFAULT_COMMAND required]"
`ff -s EXISTING_FILE.txt` and got the same error message.

**Comment by genotrance** [comment]
So ```EXISTING_DIR``` and ```EXISTING_FILE.txt``` aren't really commands so when ```fzf``` tries to run them, it fails. It needs to be an executable command like ```dir EXISTING_DIR``` or similar but you would rather use the ```-d``` flag for that.

The reason ```*.zip``` works is because ```ff``` recognizes * and replaces ```*.zip``` with ```dir /s/b *.zip```.

**Comment by step-** [comment]
Thank you. I must be too thick, but I don't understand what the phrase
```
Content to populate the fzf menu
                    file, dir or *.xyz shortcuts
                    or command to execute
```
for `-s <select>` is supposed to mean. If I understand you correctly, you're telling me that `-s` is followed by a command, and sets the environment variable FZF_DEFAULT_COMMAND. Is there anything more in the way of defining what `-s` does?

**Comment by genotrance** [comment]
I probably need to clean up that section a bit, it is a bit hard to understand what it really means.

So `ff` uses the `-s` flag to decide what to send `fzf` via the `FZF_DEFAULT_COMMAND` variable. 

Here's the code:-
```nim
if selectout == "file":
    selectout = "dir /s/b/a-d"
elif selectout == "dir":
    selectout = "dir /s/b/ad"
elif selectout.find("*") != -1 and selectout.find(" ") == -1:
    selectout = "dir /s/b " & selectout
```

If it is not `file`, `dir` or a `*.xyz` format, it just passes the command raw to `fzf`. Otherwise, it changes it as above.

**Comment by step-** [comment]
Thank you!
