### ISSUE TITLE
Open Directory of Selection in Explorer

### ISSUE THREAD

**Issue by tgaldi** [genotrance/ff#3]
I would like to do something like:

Q.name = "Open directory of selection in explorer"
Q.select = "\*.\*"
Q.action = "explorer /select,"

/select, is a switch for windows explorer to open the location of the file's path.

**Comment by genotrance** [comment]
This seems similar to #1, can you please check if that solution (last comment) meets your needs?

You could skip the `Q.select` declaration since fzf selects all files and dirs by default.

**Comment by tgaldi** [comment]
Ah, yes sorry I should have looked. Thank you. This is a great project.
