### ISSUE TITLE
Feature request: ctrl+r integration with clink

### ISSUE THREAD

**Issue by lanza** [genotrance/ff#4]
On Darwin & Linux you can replace the default history search (ctrl+r & ctrl+s) with a fzf popup that fuzzy searches your history. Clink enables ctrl+r as well as a history file. Integration with this would be amazing. I'd probably have tried to massage your code to get it to work but I don't know nim :(

**Comment by genotrance** [comment]
It would help me to understand what kind of integration you are looking for here. Can you please explain in some more detail?

**Comment by lanza** [comment]
Have you used POSIX bash to know what readline is? If so, the command.exe extension called "clink" provides command.exe with readline. 

Fzf on Darwin and Linux can hook into the readline bindings and replace the ancient history search functionality with an fzf based history search.

**Comment by genotrance** [comment]
This isn't really the goal of this tool. It simply calls fzf with the right parameters; it doesn't aim to integrate with clink. Would be awesome though, I agree!

**Comment by fcying** [comment]
You can use clink _inputrc and lua to do this.
bind c-t to run fzf and read result
_inputrc:
```
C-t:	"luafunc:fzf_file"
```
lua_script:
```
function fzf_file(rl_buffer)
	rl_buffer:insert(assert(io.popen('fzf  --height 50%')):read('*all'))
end
```
