### ISSUE TITLE
Can I cd into a directory in current CMD window?

### ISSUE THREAD

**Issue by BSDxxxx** [genotrance/ff#6]
```
c.name = "Go into selected directory"
c.select = "dir"
c.action = "cd"
```
This will open a new CMD window everytime.

**Comment by genotrance** [comment]
I believe [clink](https://mridgers.github.io/clink/) might be able to do this but ff simply calls fzf which spawns a new process. There's no way ff can take the output right now and influence the shell that spawned it.

**Comment by BSDxxxx** [comment]
@genotrance Got it ,thanks.
